# statistics that analyse in the frequency-domain (see Schoegl and Supp, 2006)
.statistics.spectral:
  spectral_granger:
      # Non-parametric Granger causality (no VAR model)
    - method: nonparametric
      fmin: 0
      fmax: 0.5
      statistic: mean