#!/bin/bash
#PBS -N SPI_troubleshooting
#PBS -q yossarian
#PBS -j oe
#PBS -o /headnode1/abry4213/github/fMRI_FeaturesDisorders/data_prep_and_QC/pyspi_QC_analysis/SPI_troubleshooting_py_pbs.out
#PBS -l select=1:ncpus=1:mem=20GB
#PBS -l walltime=2:00:00
#PBS -m abe
#PBS -M abry4213@uni.sydney.edu.au
#PBS -V

cd $$PBS_O_WORKDIR

### CHANGE TO ANY RELEVANT CONDA INIT SCRIPTS
module load Anaconda3-5.1.0
source /usr/physics/python/anaconda3/etc/profile.d/conda.sh
###

conda activate pyspi

# Verify python version
python --version

# Verify the host on which the job ran
hostname

# Change to relevant directory and run our compute script
cd /headnode1/abry4213/github/fMRI_FeaturesDisorders/data_prep_and_QC/pyspi_QC_analysis/
python SPI_troubleshooting.py > /headnode1/abry4213/github/fMRI_FeaturesDisorders/data_prep_and_QC/pyspi_QC_analysis/SPI_troubleshooting_py.out