#!/bin/bash
#PBS -N 1_pairwise_SPI_wise_null_model_fit
#PBS -j oe
#PBS -o /headnode1/abry4213/github/fMRI_FeaturesDisorders/cluster_output/UCLA_CNP_ABIDE_ASD_null_model_fits/pairwise_SPI_wise_null_model_fit_inv_prob_null_model_fit_1_out.txt
#PBS -l select=1:ncpus=1:mem=40GB
#PBS -l walltime=55:00:00
#PBS -m a
#PBS -M abry4213@uni.sydney.edu.au
#PBS -V

cd "$PBS_O_WORKDIR"

# Define directories
github_dir=/headnode1/abry4213/github/
data_path=/headnode1/abry4213/data/UCLA_CNP_ABIDE_ASD/
rdata_path=/headnode1/abry4213/data/UCLA_CNP_ABIDE_ASD/processed_data/Rdata/
mkdir -p $github_dir/fMRI_FeaturesDisorders/cluster_output/UCLA_CNP_ABIDE_ASD_null_model_fits/

# Change to relevant directory and run our compute script
/usr/physics/R/R-4.2.1/bin/Rscript ${github_dir}/fMRI_FeaturesDisorders/helper_functions/classification/Null_distributions_cluster.R \
--dataset_ID UCLA_CNP_ABIDE_ASD \
--pairwise_data_file UCLA_CNP_AROMA_2P_GMR_ABIDE_ASD_FC1000_pyspi14_filtered_zscored.Rds \
--SPI_directionality_file /headnode1/abry4213/github/fMRI_FeaturesDisorders/classification_analysis/pairwise_analysis/SPI_Direction_Info.csv \
--sample_metadata_file UCLA_CNP_ABIDE_ASD_sample_metadata.Rds \
--data_path ${data_path} \
--rdata_path ${rdata_path} \
--github_dir ${github_dir} \
--pairwise \
--num_k_folds 10 \
--output_data_dir /headnode1/abry4213/data/UCLA_CNP_ABIDE_ASD/processed_data/Rdata/UCLA_CNP_ABIDE_ASD_SPI_wise_pyspi14_inv_prob_null_model_fits/ \
--null_iter_number 1 \
--num_perms_for_iter 1 \
--pairwise_feature_set pyspi14 \
--univariate_feature_set catch22 \
--svm_kernel linear \
--grouping_var SPI \
--svm_feature_var region_pair \
--use_inv_prob_weighting \
--weighting_name inv_prob

exit

# Verify the host on which the job ran
hostname
