---
title: "Step 7: Combined Corr + Univariate"
output: 
  github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

### Source functions
```{r}
source("../helper_functions/Linear_SVM.R")
source("../helper_functions/Visualization.R")
source("../helper_functions/Null_distributions.R")
source("../helper_functions/t_test_functions.R")
rdata_path <- "D:/Virtual_Machines/Shared_Folder/PhD_work/data/scz/UCLA/Rdata/"
set.seed(127)
```

### Load data

```{r}
# Load catch22 data for current noise processing method
noise_label = "AROMA_2P"
feature_matrix <- readRDS(paste0(rdata_path, sprintf("UCLA_%s_catch22_zscored.Rds", 
                                                     noise_label)))      

# Load pyspi data
study <- "D:/Virtual_Machines/Shared_Folder/PhD_work/"
SPI_directionality <- read.csv("../6_Pairwise_ROI_analysis/SPI_Direction_Info.csv")
rdata_path_for_pyspi <- "D:/Virtual_Machines/Shared_Folder/PhD_work/data/scz/UCLA/pydata/R_files/"
all_pyspi_data <- readRDS(paste0(rdata_path_for_pyspi, "All_subject_pyspi.Rds"))
ROI_index <- read.csv(paste0(study, "data/scz/UCLA/pydata/ROI_info.csv"))
```

Isolate pearson correlation
```{r}
pyspi_pearson <- subset(all_pyspi_data, SPI == "cov_EmpiricalCovariance") %>%
  mutate(comparison = row_number()) %>%
  pivot_longer(cols = c(brain_region_1,
                        brain_region_2),
               names_to = "Region_Number",
               values_to = "Index") %>%
  left_join(ROI_index) %>%
  dplyr::select(-Index) %>%
  pivot_wider(id_cols = c("Subject_ID", "group", "SPI", "value", "comparison"),
              names_from = "Region_Number",
              values_from = "ROI") %>%
  dplyr::select(-comparison) %>%
  mutate(ROI_pair = ifelse(brain_region_1 < brain_region_2, 
                           paste0(brain_region_1, "_", brain_region_2),
                           paste0(brain_region_2, "_", brain_region_1)),
         .keep = "unused") %>%
  distinct()
```

Z-score normalize pearson correlation
```{r}
pyspi_pearson_z <- pyspi_pearson %>%
  ungroup() %>%
  group_by(SPI) %>%
  mutate(value_z = (value - mean(value, na.rm=T))/sd(value, na.rm=T), .keep = "unused") %>%
  dplyr::rename("value" = "value_z")
```


Prep datasets from long to wide and combine for SVM
```{r}
pyspi_pearson_wide <- pyspi_pearson_z %>%
  mutate(Unique_ID = paste0("SPI_pearson_", ROI_pair), .keep = "unused") %>%
  pivot_wider(id_cols = c(Subject_ID, group),
              names_from = Unique_ID, 
              values_from = "value") %>%
  drop_na() %>%
  mutate(group = ifelse(group == "CONTROL", "Control", "Schz"))

univariate_combo_wide <- feature_matrix %>%
  mutate(Unique_ID = paste0(names, "_", Brain_Region), .keep = "unused") %>%
  pivot_wider(id_cols = c(Subject_ID, group),
              names_from = Unique_ID,
              values_from = values) %>%
  drop_na()


univariate_pairwise_data_for_SVM <- left_join(univariate_combo_wide,
                                              pyspi_pearson_wide) %>%
  drop_na() %>%
  dplyr::select(-Subject_ID)
```

Run 10-fold CV unweighted linear SVM
```{r}
# Define parameters
k = 10
svm_kernel = "linear"
sample_wts = list("Control" = 1, "Schz" = 1)
use_SMOTE = FALSE
shuffle_labels = FALSE
noise_proc = "AROMA+2P"
return_all_fold_metrics = TRUE

# Run SVM
if (!file.exists(paste0(rdata_path, "Uni_and_Pairwise_Linear_SVM_CV.Rds"))) {
  combined_SVM_results <- k_fold_CV_linear_SVM(input_data = univariate_pairwise_data_for_SVM,
                                      k = k,
                                      c_values = 1,
                                      svm_kernel = svm_kernel,
                                      sample_wts = sample_wts,
                                      use_SMOTE = use_SMOTE,
                                      shuffle_labels = shuffle_labels,
                                      return_all_fold_metrics = return_all_fold_metrics) %>%
    mutate(Noise_Proc = noise_proc)
  saveRDS(combined_SVM_results, file=paste0(rdata_path, "Uni_and_Pairwise_Linear_SVM_CV.Rds"))
}
```

Run 10-fold CV inv prob-weighted linear SVM
```{r}
# Define parameters
k = 10
svm_kernel = "linear"

# Get control/schz sample props
sample_props <- univariate_pairwise_data_for_SVM %>%
  dplyr::summarise(control_prop = sum(group=="Control") / n(),
                   schz_prop = sum(group=="Schz")/n())

# Convert to sample weights based on inverse of probability
sample_wts <- list("Control" = 1/sample_props$control_prop,
                   "Schz" = 1/sample_props$schz_prop)
use_SMOTE = FALSE
shuffle_labels = FALSE
noise_proc = "AROMA+2P"
return_all_fold_metrics = TRUE

# Run SVM
if (!file.exists(paste0(rdata_path, "Uni_and_Pairwise_Linear_SVM_CV_inv_prob.Rds"))) {
  combined_SVM_results_inv_prob <- k_fold_CV_linear_SVM(input_data = univariate_pairwise_data_for_SVM,
                                      k = k,
                                      c_values = 1,
                                      svm_kernel = svm_kernel,
                                      sample_wts = sample_wts,
                                      use_SMOTE = use_SMOTE,
                                      shuffle_labels = shuffle_labels,
                                      return_all_fold_metrics = return_all_fold_metrics) %>%
    mutate(Noise_Proc = noise_proc)
  saveRDS(combined_SVM_results_inv_prob, file=paste0(rdata_path, "Uni_and_Pairwise_Linear_SVM_CV_inv_prob.Rds"))
}
```

Combine results into a plot
```{r}
plyr::rbind.fill(combined_SVM_results %>% 
                   mutate(Method = paste0(Sample_Type, ", Unweighted")),
                 combined_SVM_results_inv_prob %>%
                   mutate(Method = paste0(Sample_Type, ", Inv Prob")))  %>%
  ggplot(data=., mapping = aes(x = Method, 
                               y = balanced_accuracy,
                               color = Method)) +
  geom_boxplot() +
  ylab("Balanced Accuracy\nacross k=10 Folds") +
  xlab("Sample Type") +
  ggtitle("Balanced Accuracy for Combined Univariate and\nPearson Correlation Linear SVM with 10-fold CV") +
  theme(plot.title = element_text(hjust=0.5),
        legend.position = "none") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 15))
ggsave("plots/Combined_Pearson_Univariate_SVM_Balanced_Accuracy_CV.png",
       width = 6, height = 4, units = "in", dpi = 300)
```
