#!/bin/bash
#PBS -j oe
#PBS -o /headnode1/abry4213/github/fMRI_FeaturesDisorders/cluster_output/calculate_lm_beta_statistics_out.txt
#PBS -l select=1:ncpus=32:mem=180GB:mpiprocs=32
#PBS -l walltime=12:00:00
#PBS -q yossarian
#PBS -M abry4213@uni.sydney.edu.au
#PBS -m a
#PBS -V

cd "$PBS_O_WORKDIR"

# Load anaconda
/usr/physics/Modules/3.2.8/bin/modulecmd bash load Anaconda3-5.1.0 --silent
source /usr/physics/python/anaconda3/etc/profile.d/conda.sh 

conda activate pyspi

# Call R script to run OLS models
Rscript /headnode1/abry4213/github/fMRI_FeaturesDisorders/classification_analysis/lm_beta_statistics.R

exit

# Verify the host on which the job ran
hostname


