```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=F, message=F)
```

### Source functions
```{r}
rdata_path <- "D:/Virtual_Machines/Shared_Folder/PhD_work/data/scz/UCLA/Rdata/"
```

Load upsampled null distribution

```{r}
model_free_shuffle_null_upsampled <- readRDS(paste0(rdata_path, "Null_Model_Free_Shuffles_Upsampled.Rds"))
```


Load Step 3 ROI-wise results

```{r}
step3_ROI_wise_acc <- readRDS(paste0(rdata_path, "multivar_ROI_res_svmLinear_CV_e1071.Rds"))

# step3_ROI_wise_pvals <- readRDS(paste0(rdata_path, "UCLA_region_wise_SVM_caret_upsampled_pvals.Rds"))
# step3_ROI_wise_res <- left_join(step3_ROI_wise_acc, step3_ROI_wise_pvals) %>%
step3_ROI_wise_res <- step3_ROI_wise_acc %>%
  dplyr::select(Brain_Region, Noise_Proc, accuracy) %>%
  filter(Noise_Proc == "AROMA+2P") %>%
  mutate(accuracy = 100*round(accuracy, 4),
         Method = "i: ROI-wise") %>%
  arrange(desc(accuracy))
```


Load Step 4 Feature-wise results

```{r}
step4_feature_wise_acc <- readRDS(paste0(rdata_path, "feature_wise_multi_ROI_svmLinear_CV_e1071.Rds"))

step4_feature_wise_res <- step4_feature_wise_acc %>%
  dplyr::select(catch22_Feature, Noise_Proc, accuracy) %>%
  filter(Noise_Proc == "AROMA+2P") %>%
  mutate(accuracy = 100*round(accuracy, 4),
         Method = "ii: Feature-wise") %>%
  arrange(desc(accuracy))

# step4_feature_wise_pvals <- readRDS(paste0(rdata_path, "UCLA_feature_wise_SVM_caret_upsampled_pvals.Rds"))
# step4_feature_wise_res <- left_join(step4_feature_wise_acc, step4_feature_wise_pvals) %>%
#   dplyr::select(catch22_Feature, Noise_Proc, accuracy, acc_p, acc_p_adj) %>%
#   filter(Noise_Proc == "AROMA+2P+DiCER") %>%
#   mutate(accuracy = 100*round(accuracy, 4),
#          Method = "ii: Feature-wise") %>%
#   arrange(desc(accuracy))
```

Load Step 5 Combo-wise results

```{r}
source("5_ROI_and_feature_wise_analysis/ROI_and_feature_analysis_functions.R")
step5_combo_wise_acc <- readRDS(paste0(rdata_path, "feature_ROI_wise_multi_ROI_svmLinear_CV_e1071.Rds"))

step5_combo_wise_res <- step5_combo_wise_acc %>%
  dplyr::select(Noise_Proc, accuracy) %>%
  filter(Noise_Proc == "AROMA+2P") %>%
  mutate(accuracy = 100*round(accuracy, 4),
         Method = "iii: Combo-wise") %>%
  arrange(desc(accuracy))

# step5_combo_wise_pvals <- readRDS(paste0(rdata_path, "UCLA_feature_ROI_wise_SVM_caret_upsampled_pvals.Rds"))
# 
# step5_combo_wise_res <- left_join(step5_combo_wise_acc, step5_combo_wise_pvals) %>%
#   dplyr::select(Noise_Proc, accuracy, acc_p, acc_p_adj) %>%
#   filter(Noise_Proc == "AROMA+2P+DiCER") %>%
#   mutate(accuracy = 100*round(accuracy, 4),
#          Method = "iii: Combo-wise") %>%
#   arrange(desc(accuracy))
```


```{r}
do.call(plyr::rbind.fill,
                    list(step3_ROI_wise_res,
                         step4_feature_wise_res,
                         step5_combo_wise_res)) %>%
  mutate(Method = factor(Method, levels = c("i: ROI-wise",
                                            "ii: Feature-wise",
                                            "iii: Combo-wise"))) %>%
  ggplot(data=., mapping=aes(x=accuracy, fill=Method)) +
  geom_histogram(alpha=0.6, position="identity") +
  ylab("Number of Trials") +
  xlab("10-fold CV Accuracy") +
  theme(axis.text = element_text(size=7),
        legend.text = element_text(size=7),
        axis.title = element_text(size=8),
        legend.title=element_text(size=8),
        legend.position = "bottom") +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))
ggsave("Figure1.png", width=898, height=700, units="px", dpi=300)
```

