#!/bin/bash
#PBS -q yossarian
#PBS -N 76_univariate_Feature_wise_null_model_fit
#PBS -j oe
#PBS -o /headnode1/abry4213/github//fMRI_FeaturesDisorders/cluster_output/ABIDE_ASD_null_model_fits/univariate_Feature_wise_null_model_fit_inv_prob_null_model_fit_76_out.txt
#PBS -l select=1:ncpus=1:mem=20GB
#PBS -l walltime=12:00:00
#PBS -m a
#PBS -M abry4213@uni.sydney.edu.au
#PBS -V

cd "$PBS_O_WORKDIR"

# Define directories
github_dir=/headnode1/abry4213/github/
data_path=/headnode1/abry4213/data/ABIDE_ASD/
rdata_path=/headnode1/abry4213/data/ABIDE_ASD/processed_data/Rdata/
mkdir -p $github_dir/fMRI_FeaturesDisorders/cluster_output/ABIDE_ASD_null_model_fits/

# Change to relevant directory and run our compute script
/usr/physics/R/R-4.2.1/bin/Rscript ${github_dir}/fMRI_FeaturesDisorders/helper_functions/classification/Null_distributions_cluster.R \
--dataset_ID ABIDE_ASD \
--pairwise_data_file PAIRWISE_DATA_FILE \
--data_path ${data_path} \
--rdata_path ${rdata_path} \
--github_dir ${github_dir} \
--sample_metadata_file ABIDE_ASD_sample_metadata.Rds \
--SPI_directionality_file SPI_DIRECTIONALITY_FILE \
--univariate --num_k_folds 10 \
--output_data_dir /headnode1/abry4213/data/ABIDE_ASD/processed_data/Rdata/ABIDE_ASD_Feature_wise_catch22_inv_prob_null_model_fits/ \
--null_iter_number 76 \
--num_perms_for_iter 10 \
--pairwise_feature_set pyspi14 \
--univariate_feature_set catch22 \
--noise_proc FC1000 \
--svm_kernel linear \
--grouping_var Feature \
--svm_feature_var Brain_Region \
--weighting_name inv_prob \
--use_inv_prob_weighting

exit

# Verify the host on which the job ran
hostname


