#!/bin/bash
#PBS -q defaultQ
#PBS -j oe
#PBS -o /headnode1/abry4213/github/fMRI_FeaturesDisorders/cluster_output/normalisation_comparison_out.txt
#PBS -l select=1:ncpus=1:mem=20GB
#PBS -l walltime=6:00:00
#PBS -M abry4213@uni.sydney.edu.au
#PBS -m a
#PBS -V

cd "$PBS_O_WORKDIR"

# Call R script
Rscript /headnode1/abry4213/github/fMRI_FeaturesDisorders/prep_data_and_QC/normalisation_comparison.R

exit

# Verify the host on which the job ran
hostname


