#!/bin/bash
#PBS -q defaultQ
#PBS -j oe
#PBS -o /headnode1/abry4213/github/fMRI_FeaturesDisorders/cluster_output/compute_regional_fALFF_out.txt
#PBS -l select=1:ncpus=1:mem=30GB
#PBS -l walltime=24:00:00
#PBS -M abry4213@uni.sydney.edu.au
#PBS -m a
#PBS -V

cd "$PBS_O_WORKDIR" 

# Load python
/usr/physics/Modules/3.2.8/bin/modulecmd bash load Anaconda3-5.1.0 --silent
source /usr/physics/python/anaconda3/etc/profile.d/conda.sh 
conda activate pyspi

# Load matlab
/usr/physics/Modules/3.2.8/bin/modulecmd bash load Matlab2019b

# Define directories
export github_dir=/headnode1/abry4213/github/
mkdir -p $github_dir/fMRI_FeaturesDisorders/cluster_output/

# Run python script to convert .mat to .feather file
export UCLA_CNP_file_base="/headnode1/abry4213/data/UCLA_CNP/raw_data/UCLA_CNP_AROMA_2P_GMR_fMRI_TS"
python3 $github_dir/fMRI_FeaturesDisorders/prep_data_and_QC/feather_to_mat.py $UCLA_CNP_file_base mat
export ABIDE_ASD_file_base="/headnode1/abry4213/data/ABIDE_ASD/raw_data/ABIDE_ASD_FC1000_fMRI_TS"
python3 $github_dir/fMRI_FeaturesDisorders/prep_data_and_QC/feather_to_mat.py $ABIDE_ASD_file_base mat

# # Run matlab fALFF script
/usr/physics/matlab/matlab2019b/bin/matlab -nodisplay -singleCompThread -r "compute_regional_fALFF, exit"

# Run python script to convert .mat to .feather file
export UCLA_CNP_file_base="/headnode1/abry4213/data/UCLA_CNP/processed_data/UCLA_CNP_AROMA_2P_GMR_ALFF_fALFF"
export UCLA_CNP_subjects="/headnode1/abry4213/data/UCLA_CNP/processed_data/UCLA_CNP_filtered_sample_info_AROMA_2P_GMR_final.feather"
python3 $github_dir/fMRI_FeaturesDisorders/prep_data_and_QC/feather_to_mat.py $UCLA_CNP_file_base feather UCLA_CNP AROMA+2P+GMR $UCLA_CNP_subjects
export ABIDE_ASD_file_base="/headnode1/abry4213/data/ABIDE_ASD/processed_data/ABIDE_ASD_FC1000_ALFF_fALFF"
export ABIDE_ASD_subjects="/headnode1/abry4213/data/ABIDE_ASD/processed_data/ABIDE_ASD_filtered_sample_info_FC1000_final.feather"
python3 $github_dir/fMRI_FeaturesDisorders/prep_data_and_QC/feather_to_mat.py $ABIDE_ASD_file_base feather ABIDE_ASD FC1000 $ABIDE_ASD_subjects

# exit

# Verify the host on which the job ran
hostname