#!/bin/bash
#PBS -q yossarian
#PBS -j oe
#PBS -o /headnode1/abry4213/github/fMRI_FeaturesDisorders/cluster_output/normalisation_comparison_out.txt
#PBS -l select=1:ncpus=1:mem=40GB
#PBS -l walltime=6:00:00
#PBS -M abry4213@uni.sydney.edu.au
#PBS -m a
#PBS -V

cd "$PBS_O_WORKDIR"

# Load anaconda
/usr/physics/Modules/3.2.8/bin/modulecmd bash load Anaconda3-5.1.0 --silent
source /usr/physics/python/anaconda3/etc/profile.d/conda.sh 

conda activate pyspi

# Call R script
Rscript /headnode1/abry4213/github/fMRI_FeaturesDisorders/prep_data_and_QC/normalisation_comparison.R

exit

# Verify the host on which the job ran
hostname


