#!/bin/bash
#PBS -N movement_SVM
#PBS -o /headnode1/abry4213/github/fMRI_FeaturesDisorders/cluster_output/movement_SVM.out
#PBS -j oe
#PBS -q yossarian
#PBS -m a
#PBS -M abry4213@uni.sydney.edu.au
#PBS -l select=1:ncpus=1:mem=40GB
#PBS -l walltime=24:00:00
#PBS -V

cd "$PBS_O_WORKDIR" 

# Define directories
github_dir=/headnode1/abry4213/github/fMRI_FeaturesDisorders
mkdir -p $github_dir/cluster_output/

# Run script
Rscript $github_dir/data_prep_and_QC/movement/SVMs_with_movement.R 

exit

# Verify the host on which the job ran
hostname


