---
output: html_document
params:
  data_path: ""
  github_dir: ""
  dataset_ID: ""
  ggseg_atlas: ""
  univariate_feature_set: ""
  pairwise_feature_set: ""
  brain_region_file: ""
  noise_procs: ""
  noise_proc_for_null: ""

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning=F, message=F)
```

```{r}
library(tidyverse)
library(icesTAF)
library(broom)
library(ggseg)
library(ggsegHO)
# library(ggsegExtra)
library(tidyverse)
library(plotly)
# library(ggseg3d)
# library(ungeviz)
# library(reshape2)
library(patchwork)
library(cowplot)

theme_set(theme_cowplot())
```


```{r}
# Parse params
data_path <- params$data_path
github_dir <- params$github_dir
dataset_ID <- params$dataset_ID
ggseg_atlas <- params$ggseg_atlas
univariate_feature_set <- params$univariate_feature_set
pairwise_feature_set <- params$pairwise_feature_set
noise_procs <- params$noise_procs
noise_proc_for_null <- params$noise_proc_for_null
brain_region_file <- params$brain_region_file

# univariate_feature_set <- "catch22"
# pairwise_feature_set <- "pyspi14"
# subject_csv <- "participants.csv"
# github_dir <- "D:/Virtual_Machines/Shared_Folder/github/fMRI_FeaturesDisorders/"
# github_dir <- "~/github/fMRI_FeaturesDisorders/"

# UCLA schizophrenia
# data_path <- "D:/Virtual_Machines/Shared_Folder/PhD_work/data/UCLA_Schizophrenia/"
# data_path <- "~/data/UCLA_Schizophrenia/"
# dataset_ID <- "UCLA_Schizophrenia"
# noise_procs <- c("AROMA+2P", "AROMA+2P+GMR", "AROMA+2P+DiCER")
# noise_proc_for_null <- "AROMA+2P+GMR"
# ggseg_atlas = "DK"
# brain_region_file = "Brain_Region_info.csv"

# ABIDE ASD
# data_path <- "D:/Virtual_Machines/Shared_Folder/PhD_work/data/ABIDE_ASD/"
# data_path <- "~/data/ABIDE_ASD/"
# dataset_ID <- "ABIDE_ASD"
# noise_procs <- c("FC1000")
# noise_proc_for_null <- "FC1000"
# ggseg_atlas = "HO"
# brain_region_file = "Harvard_Oxford_cort_prob_2mm_ROI_lookup.csv"

rdata_path <- paste0(data_path, "processed_data/Rdata/")
plot_path <- paste0(data_path, "plots/")
brain_region_lookup <- read.csv(paste0(data_path, brain_region_file))
```

```{r}
# Source null distribution functions
source(paste0(github_dir, "helper_functions/Visualization.R"))
```


```{r, results="asis"}
cat("## Univariate linear SVM results for", dataset_ID, "\n")
```


### Significant results by brain region
```{r, fig.width=6,fig.height=4}
# Main vs. null histogram
univariate_region_wise_full <- readRDS(paste0(rdata_path, 
                                              "ROI_wise_CV_linear_SVM_", 
                                              univariate_feature_set,
                                              "_inv_prob_balacc.Rds")) %>%
  dplyr::filter(Noise_Proc == noise_proc_for_null) 

univariate_region_wise_main <- univariate_region_wise_full %>%
  group_by(grouping_var, Sample_Type, Noise_Proc, repeat_number) %>%
  summarise(mean_balanced_accuracy = mean(balanced_accuracy, na.rm=T)) %>%
  group_by(grouping_var, Sample_Type, Noise_Proc) %>%
  summarise(balanced_accuracy = mean(mean_balanced_accuracy, na.rm=T),
            SD = sd(mean_balanced_accuracy, na.rm=T))

# UCLA_Schizophrenia_ROI_wise_model_permutation_null_catch22_inv_prob.Rds
univariate_region_wise_null <- readRDS(paste0(rdata_path, dataset_ID,
                                              "_ROI_wise_model_permutation_null_", 
                                              univariate_feature_set,
                                              "_inv_prob.Rds"))

# Pooled empirical null p-values
univariate_region_wise_pvals <- readRDS(paste0(rdata_path, 
                                               "ROI_wise_CV_linear_SVM_model_permutation_null_", 
                                               univariate_feature_set,
                                               "_inv_prob_pvals.Rds"))

# Define xmin and xmax
xmin = 0.99 * min(c(min(univariate_region_wise_main$balanced_accuracy)),
                  c(min(univariate_region_wise_null$balanced_accuracy)))

xmax = 1.01 * max(c(max(univariate_region_wise_main$balanced_accuracy)),
                  c(max(univariate_region_wise_null$balanced_accuracy)))

plot_main_vs_null_bal_acc(main_res = univariate_region_wise_main,
                          null_res = univariate_region_wise_null,
                          pvals = univariate_region_wise_pvals,
                          noise_proc = noise_proc_for_null,
                          xmin = xmin, 
                          xmax = xmax,
                          plot_type = "histogram",
                          grouping_type = "Region-wise",
                          result_color = "#F0224B") +
  ggtitle("Results vs. Empirical Null Model") +
  theme(legend.position = "right",
        plot.title = element_text(size=13))
```

```{r}
univariate_region_wise_sig <- univariate_region_wise_pvals %>%
  filter(bal_acc_p_adj < 0.05) %>%
  ungroup() %>%
  dplyr::select(grouping_var, balanced_accuracy, bal_acc_p_adj) %>%
  left_join(., univariate_region_wise_main)

univariate_region_wise_sig %>%
  arrange(bal_acc_p_adj, desc(balanced_accuracy)) %>%
  dplyr::select(grouping_var, balanced_accuracy, SD, bal_acc_p_adj) %>%
  mutate(balanced_accuracy = paste0(round(100*balanced_accuracy, 2), " ± ", round(100*SD, 2)),
         bal_acc_p_adj = format(bal_acc_p_adj, scientific = T, 
                                big.mark = ",")) %>%
  dplyr::select(-SD) %>%
  dplyr::rename("Brain Region" = "grouping_var",
                "Balanced Accuracy ± SD" = "balanced_accuracy",
                "BH-adjusted p value" = "bal_acc_p_adj") %>%
  knitr::kable(.) %>%
  kableExtra::kable_styling(full_width=F)
```


```{r, fig.width=6,fig.height=2}
# Brain plot of significant regions
if (ggseg_atlas == "DK") {
  ggseg_lookup <- dk$data
  
  cortex_data <- univariate_region_wise_sig %>%
    dplyr::rename("Brain_Region" = "grouping_var") %>%
    dplyr::mutate(Brain_Region = str_replace_all(Brain_Region, "_", " ")) %>%
    left_join(., brain_region_lookup) %>%
    dplyr::select(ggseg, balanced_accuracy) %>%
    dplyr::rename("label" = "ggseg") %>%
    mutate(label = ifelse(str_detect(label, "ctx-"),
                          gsub("-", "_", label),
                          label)) %>%
    mutate(label = gsub("ctx_", "", label)) %>%
    left_join(., ggseg_lookup) 
  
  atlas_to_plot = "dk"
  
} else if (ggseg_atlas == "HO") {
  ggseg_lookup <- hoCort$data
  
  cortex_data <- univariate_region_wise_sig %>%
    dplyr::rename("Brain_Region" = "grouping_var") %>%
    dplyr::mutate(Brain_Region = str_replace_all(Brain_Region, "_", " ")) %>%
    left_join(., brain_region_lookup) %>%
    dplyr::select(ggseg, balanced_accuracy) %>%
    dplyr::rename("region" = "ggseg") %>%
    left_join(., ggseg_lookup) 
  
  atlas_to_plot = "hoCort"
}

cortex_data <- cortex_data %>%
  filter(!is.na(region)) %>%
  mutate(fillyes = T) %>%
  distinct()

cortex_data %>%
  dplyr::select(region, hemi, fillyes) %>%
  distinct() %>%
  ggseg(atlas=atlas_to_plot, mapping=aes(fill = fillyes),
        position="dispersed", colour="darkgrey") +
  scale_fill_manual(values = c("#F0224B"), na.value = NA) +
  labs(fill = "Balanced Accuracy") +
  theme_void() +
  theme(plot.title = element_blank(),
        legend.position = "none") 
```

```{r, results="asis"}
cat("### Significant results by", univariate_feature_set, "feature\n")
```

```{r, fig.width=6,fig.height=4}
# Main vs. null histogram
univariate_feature_wise_main <- readRDS(paste0(rdata_path, 
                                               "Feature_wise_CV_linear_SVM_", 
                                               univariate_feature_set,
                                               "_inv_prob_balacc.Rds")) %>%
  dplyr::filter(Noise_Proc == noise_proc_for_null) %>%
  group_by(grouping_var, Sample_Type, Noise_Proc, repeat_number) %>%
  summarise(mean_balanced_accuracy = mean(balanced_accuracy, na.rm=T)) %>%
  group_by(grouping_var, Sample_Type, Noise_Proc) %>%
  summarise(balanced_accuracy = mean(mean_balanced_accuracy, na.rm=T),
            SD = sd(mean_balanced_accuracy, na.rm=T))

# UCLA_Schizophrenia_Feature_wise_model_permutation_null_catch22_inv_prob.Rds
univariate_feature_wise_null <- readRDS(paste0(rdata_path, dataset_ID,
                                               "_Feature_wise_model_permutation_null_", 
                                               univariate_feature_set,
                                               "_inv_prob.Rds"))

# Pooled empirical null p-values
univariate_feature_wise_pvals <- readRDS(paste0(rdata_path, 
                                                "Feature_wise_CV_linear_SVM_model_permutation_null_", 
                                                univariate_feature_set,
                                                "_inv_prob_pvals.Rds"))

# Define xmin and xmax
xmin = 0.99 * min(c(min(univariate_feature_wise_main$balanced_accuracy)),
                  c(min(univariate_feature_wise_null$balanced_accuracy)))

xmax = 1.01 * max(c(max(univariate_feature_wise_main$balanced_accuracy)),
                  c(max(univariate_feature_wise_null$balanced_accuracy)))

plot_main_vs_null_bal_acc(main_res = univariate_feature_wise_main,
                          null_res = univariate_feature_wise_null,
                          pvals = univariate_feature_wise_pvals,
                          noise_proc = noise_proc_for_null,
                          xmin = xmin, 
                          xmax = xmax,
                          plot_type = "histogram",
                          grouping_type = "Feature-wise",
                          result_color = "#5C86C6") +
  ggtitle("Results vs. Empirical Null Model") +
  theme(legend.position = "right",
        plot.title = element_text(size=13))
```

```{r}
univariate_feature_wise_sig <- univariate_feature_wise_pvals %>%
  filter(bal_acc_p_adj < 0.05) %>%
  ungroup() %>%
  dplyr::select(grouping_var, balanced_accuracy, bal_acc_p_adj) %>%
  left_join(., univariate_feature_wise_main)

univariate_feature_wise_sig %>%
  arrange(bal_acc_p_adj, desc(balanced_accuracy)) %>%
  dplyr::select(grouping_var, balanced_accuracy, SD, bal_acc_p_adj) %>%
  mutate(balanced_accuracy = paste0(round(100*balanced_accuracy, 2), " ± ", round(100*SD, 2)),
         bal_acc_p_adj = format(bal_acc_p_adj, scientific = T, 
                                big.mark = ",")) %>%
  dplyr::select(-SD) %>%
  dplyr::rename("catch22 feature" = "grouping_var",
                "Balanced Accuracy ± SD" = "balanced_accuracy",
                "BH-adjusted p value" = "bal_acc_p_adj") %>%
  knitr::kable(.) %>%
  kableExtra::kable_styling(full_width=F)
```

```{r, results="asis"}
cat("### Significant results by", univariate_feature_set, "feature + Brain Region combo\n")
```

```{r, fig.width=6,fig.height=4}
# Main vs. null histogram
univariate_combo_wise_main <- readRDS(paste0(rdata_path, 
                                             "Combo_wise_CV_linear_SVM_", 
                                             univariate_feature_set,
                                             "_inv_prob_balacc.Rds")) %>%
  dplyr::filter(Noise_Proc == noise_proc_for_null) %>%
  group_by(grouping_var, Sample_Type, Noise_Proc, repeat_number) %>%
  summarise(mean_balanced_accuracy = mean(balanced_accuracy, na.rm=T)) %>%
  group_by(grouping_var, Sample_Type, Noise_Proc) %>%
  summarise(balanced_accuracy = mean(mean_balanced_accuracy, na.rm=T),
            SD = sd(mean_balanced_accuracy, na.rm=T))

# UCLA_Schizophrenia_Combo_wise_model_permutation_null_catch22_inv_prob.Rds
univariate_combo_wise_null <- readRDS(paste0(rdata_path, dataset_ID,
                                             "_Combo_wise_model_permutation_null_", 
                                             univariate_feature_set,
                                             "_inv_prob.Rds"))

# Pooled empirical null p-values
univariate_combo_wise_pvals <- readRDS(paste0(rdata_path, 
                                              "Combo_wise_CV_linear_SVM_model_permutation_null_", 
                                              univariate_feature_set,
                                              "_inv_prob_pvals.Rds"))

# Define xmin and xmax
xmin = 0.99 * min(c(min(univariate_combo_wise_main$balanced_accuracy)),
                  c(min(univariate_combo_wise_null$balanced_accuracy)))

xmax = 1.01 * max(c(max(univariate_combo_wise_main$balanced_accuracy)),
                  c(max(univariate_combo_wise_null$balanced_accuracy)))

plot_main_vs_null_bal_acc(main_res = univariate_combo_wise_main,
                          null_res = univariate_combo_wise_null,
                          pvals = univariate_combo_wise_pvals,
                          noise_proc = noise_proc_for_null,
                          xmin = xmin, 
                          xmax = xmax,
                          line_only = TRUE,
                          plot_type = "histogram",
                          density = F,
                          grouping_type = "Combo-wise",
                          result_color = "#9B51B4") +
  ggtitle("Results vs. Empirical Null Model") +
  theme(legend.position = "right",
        plot.title = element_text(size=13))
```

```{r}
univariate_combo_wise_sig <- univariate_combo_wise_pvals %>%
  filter(bal_acc_p_adj < 0.05) %>%
  ungroup() %>%
  dplyr::select(grouping_var, balanced_accuracy, bal_acc_p_adj) %>%
  left_join(., univariate_combo_wise_main, by=c("grouping_var")) %>%
  dplyr::select(-balanced_accuracy.x) %>%
  dplyr::rename("balanced_accuracy" = "balanced_accuracy.y")

univariate_combo_wise_sig %>%
  arrange(bal_acc_p_adj, desc(balanced_accuracy)) %>%
  dplyr::select(grouping_var, balanced_accuracy, SD, bal_acc_p_adj) %>%
  mutate(balanced_accuracy = paste0(round(100*balanced_accuracy, 2), " ± ", round(100*SD, 2)),
         bal_acc_p_adj = format(bal_acc_p_adj, scientific = T, 
                                big.mark = ",")) %>%
  dplyr::select(-SD) %>%
  dplyr::rename("Region/Feature Combo" = "grouping_var",
                "Balanced Accuracy ± SD" = "balanced_accuracy",
                "BH-adjusted p value" = "bal_acc_p_adj") %>%
  knitr::kable(.) %>%
  kableExtra::kable_styling(full_width=F)
```



```{r, results="asis"}
cat("## Pairwise linear SVM results for", dataset_ID, "\n")
```

### Significant results by SPI
```{r, fig.width=6,fig.height=4}
tryCatch({
  # Main vs. null histogram
  SPI_wise_main_full <- readRDS(paste0(rdata_path, 
                                  "SPI_wise_CV_linear_SVM_", 
                                  pairwise_feature_set,
                                  "_inv_prob_balacc.Rds")) %>%
    dplyr::filter(Noise_Proc == noise_proc_for_null) 
  
  SPI_wise_main <- SPI_wise_main_full %>%
    group_by(grouping_var, Sample_Type, Noise_Proc, repeat_number) %>%
    summarise(mean_balanced_accuracy = mean(balanced_accuracy, na.rm=T)) %>%
    group_by(grouping_var, Sample_Type, Noise_Proc) %>%
    summarise(balanced_accuracy = mean(mean_balanced_accuracy, na.rm=T),
              SD = sd(mean_balanced_accuracy, na.rm=T))
  
  # UCLA_Schizophrenia_ROI_wise_model_permutation_null_catch22_inv_prob.Rds
  SPI_wise_null <- readRDS(paste0(rdata_path, dataset_ID,
                                  "_SPI_wise_model_permutation_null_", 
                                  pairwise_feature_set,
                                  "_inv_prob.Rds"))
  
  # Pooled empirical null p-values
  SPI_wise_pvals <- readRDS(paste0(rdata_path, 
                                   "SPI_wise_CV_linear_SVM_model_permutation_null_", 
                                   pairwise_feature_set,
                                   "_inv_prob_pvals.Rds"))
  
  # Define xmin and xmax
  xmin = 0.99 * min(c(min(SPI_wise_main$balanced_accuracy)),
                    c(min(SPI_wise_null$balanced_accuracy)))
  
  xmax = 1.01 * max(c(max(SPI_wise_main$balanced_accuracy)),
                    c(max(SPI_wise_null$balanced_accuracy)))
  
  plot_main_vs_null_bal_acc(main_res = SPI_wise_main,
                            null_res = SPI_wise_null,
                            pvals = SPI_wise_pvals,
                            noise_proc = noise_proc_for_null,
                            xmin = xmin, 
                            xmax = xmax,
                            plot_type = "histogram",
                            grouping_type = "SPI-wise",
                            result_color = "darkgoldenrod1") +
    ggtitle("Results vs. Empirical Null Model") +
    theme(legend.position = "right",
          plot.title = element_text(size=13))
}, error = function(e) e)
```


```{r}
tryCatch({
  SPI_wise_sig <- SPI_wise_pvals %>%
    filter(bal_acc_p_adj < 0.05) %>%
    ungroup() %>%
    dplyr::select(grouping_var, balanced_accuracy, bal_acc_p_adj) %>%
    left_join(., SPI_wise_main, by=c("grouping_var")) %>%
    dplyr::select(-balanced_accuracy.x) %>%
    dplyr::rename("balanced_accuracy" = "balanced_accuracy.y")
  
  SPI_wise_sig %>%
    arrange(bal_acc_p_adj, desc(balanced_accuracy)) %>%
    dplyr::select(grouping_var, balanced_accuracy, SD, bal_acc_p_adj) %>%
    mutate(balanced_accuracy = paste0(round(100*balanced_accuracy, 2), " ± ", round(100*SD, 2)),
           bal_acc_p_adj = format(bal_acc_p_adj, scientific = T, 
                                  big.mark = ",")) %>%
    dplyr::select(-SD) %>%
    dplyr::rename("pyspi SPI" = "grouping_var",
                  "Balanced Accuracy ± SD" = "balanced_accuracy",
                  "BH-adjusted p value" = "bal_acc_p_adj") %>%
    knitr::kable(.) %>%
    kableExtra::kable_styling(full_width=F)
}, error = function(e) e)
```



```{r, results="asis"}
cat("## Univariate-Pairwise combo linear SVM results for", dataset_ID, "\n")
```

### Significant results by SPI + univariate combo
```{r, fig.width=6,fig.height=4}
tryCatch({
  # Main vs. null histogram
  SPI_combo_wise_main_full <- readRDS(paste0(rdata_path, 
                                        "univariate_", univariate_feature_set,
                                        "_pairwise_", pairwise_feature_set,
                                        "_CV_linear_SVM_inv_prob_balacc.Rds")) %>%
    dplyr::filter(Noise_Proc == noise_proc_for_null)  %>%
    dplyr::rename("grouping_var" = "SPI")
  
  SPI_combo_wise_main <- SPI_combo_wise_main_full %>%
    group_by(grouping_var, Sample_Type, Noise_Proc, repeat_number) %>%
    summarise(mean_balanced_accuracy = mean(balanced_accuracy, na.rm=T)) %>%
    group_by(grouping_var, Sample_Type, Noise_Proc) %>%
    summarise(balanced_accuracy = mean(mean_balanced_accuracy, na.rm=T),
              SD = sd(mean_balanced_accuracy, na.rm=T))
  
  SPI_combo_wise_null <- readRDS(paste0(rdata_path, dataset_ID,
                                        "_univariate_", univariate_feature_set,
                                        "_pairwise_", pairwise_feature_set, 
                                        "_model_permutation_null_inv_prob.Rds"))
  
  # Pooled empirical null p-values
  SPI_combo_wise_pvals <- readRDS(paste0(rdata_path,
                                         "univariate_", univariate_feature_set,
                                         "_pairwise_", pairwise_feature_set,
                                         "_CV_linear_SVM_model_permutation_null_inv_prob_pvals.Rds"))
  
  # Define xmin and xmax
  xmin = 0.99 * min(c(min(SPI_combo_wise_main$balanced_accuracy)),
                    c(min(SPI_combo_wise_null$balanced_accuracy)))
  
  xmax = 1.01 * max(c(max(SPI_combo_wise_main$balanced_accuracy)),
                    c(max(SPI_combo_wise_null$balanced_accuracy)))
  
  plot_main_vs_null_bal_acc(main_res = SPI_combo_wise_main,
                            null_res = SPI_combo_wise_null,
                            pvals = SPI_combo_wise_pvals,
                            noise_proc = noise_proc_for_null,
                            xmin = xmin, 
                            xmax = xmax,
                            plot_type = "histogram",
                            grouping_type = "SPI-wise",
                            result_color = "limegreen") +
    ggtitle("Results vs. Empirical Null Model") +
    theme(legend.position = "right",
          plot.title = element_text(size=13))
}, error = function(e) e)
```


```{r}
tryCatch({
  SPI_combo_wise_sig <- SPI_combo_wise_pvals %>%
    filter(bal_acc_p_adj < 0.05) %>%
    ungroup() %>%
    dplyr::select(grouping_var, balanced_accuracy, bal_acc_p_adj) %>%
    left_join(., SPI_combo_wise_main, by=c("grouping_var")) %>%
    dplyr::select(-balanced_accuracy.x) %>%
    dplyr::rename("balanced_accuracy" = "balanced_accuracy.y")
  
  SPI_combo_wise_sig %>%
    arrange(bal_acc_p_adj, desc(balanced_accuracy)) %>%
    dplyr::select(grouping_var, balanced_accuracy, SD, bal_acc_p_adj) %>%
    mutate(balanced_accuracy = paste0(round(100*balanced_accuracy, 2), " ± ", round(100*SD, 2)),
           bal_acc_p_adj = format(bal_acc_p_adj, scientific = T, 
                                  big.mark = ",")) %>%
    dplyr::select(-SD) %>%
    dplyr::rename("SPI with Univariate Combo" = "grouping_var",
                  "Balanced Accuracy ± SD" = "balanced_accuracy",
                  "BH-adjusted p value" = "bal_acc_p_adj") %>%
    knitr::kable(.) %>%
    kableExtra::kable_styling(full_width=F)
}, error = function(e) e)
```

```{r}
# Find which SPIs are statistically different with vs without univariate
# combo-wise information
sig_SPIs_diff <- SPI_wise_main_full %>% 
  mutate(Analysis = "SPI") %>%
  plyr::rbind.fill(., SPI_combo_wise_main_full %>% 
                     mutate(Analysis = "SPI + Combo")) %>%
  mutate(Analysis = factor(Analysis, levels = c("SPI + Combo", "SPI"))) %>%
  group_by(grouping_var, Analysis, repeat_number) %>%
  summarise(mean_balac = mean(balanced_accuracy, na.rm=T)) %>%
  dplyr::rename("balanced_accuracy" = "mean_balac") %>%
  arrange(repeat_number) %>%
  nest(data = -grouping_var) %>%
  mutate(test = map(data, ~ t.test(balanced_accuracy ~ Analysis, data = .x, paired=T)),
         tidied = map(test, tidy)) %>%
  unnest(tidied) %>%
  ungroup() %>%
  mutate(p.adj = p.adjust(p.value, method="BH")) %>%
  filter(p.adj < 0.05) %>%
  dplyr::select(grouping_var, estimate, statistic, p.value, p.adj) 

sig_SPIs_diff %>%
  dplyr::rename("SPI" = "grouping_var",
                "Mean Difference" = "estimate",
                "T-statistic" = "statistic",
                "p-value" = "p.value",
                "BH" = "p.adj") %>%
  knitr::kable(.) %>%
  kableExtra::kable_styling(full_width=F)
```


```{r, fig.width=8,fig.height=4}
# Spaghetti plot comparing SPIs with vs without univariate combo info,
# Only those with a significant difference
SPI_combo_wise_main %>%
  mutate(Analysis = "SPI + Univariate Combo") %>%
  plyr::rbind.fill(., SPI_wise_main %>% mutate(Analysis = "SPI")) %>%
  filter(grouping_var %in% sig_SPIs_diff$grouping_var) %>%
  mutate(grouping_var = fct_reorder(grouping_var, balanced_accuracy, .fun=max,
                                    .desc=T)) %>%
  ggplot(data=., mapping=aes(x=Analysis, 
                             y=balanced_accuracy, 
                             group=grouping_var,
                             color = grouping_var)) +
  geom_line(size=1.5) +
  ylab("10-repeat 10-fold CV Balanced Accuracy") +
  xlab("Pairwise Analysis Type") +
  labs(color = "SPI")
```


```{r}
# Summarise mean of null distributions 
region_wise_null_mean <- univariate_region_wise_null %>%
  ungroup() %>%
  summarise(mean_balacc = mean(balanced_accuracy)) %>%
  mutate(method = "Univariate Region-wise")

feature_wise_null_mean <- univariate_feature_wise_null %>%
  ungroup() %>%
  summarise(mean_balacc = mean(balanced_accuracy)) %>%
  mutate(method = "Univariate Feature-wise")

combo_wise_null_mean <- univariate_combo_wise_null %>%
  ungroup() %>%
  summarise(mean_balacc = mean(balanced_accuracy)) %>%
  mutate(method = "Univariate Combo-wise")

SPI_wise_null_mean <- SPI_wise_null %>%
  ungroup() %>%
  summarise(mean_balacc = mean(balanced_accuracy)) %>%
  mutate(method = "Pairwise SPI-wise")

SPI_combo_wise_null_mean <- SPI_combo_wise_null %>%
  ungroup() %>%
  summarise(mean_balacc = mean(balanced_accuracy)) %>%
  mutate(method = "Pairwise Combo-wise")

do.call(plyr::rbind.fill, list(region_wise_null_mean,
                               feature_wise_null_mean,
                               combo_wise_null_mean,
                               SPI_wise_null_mean,
                               SPI_combo_wise_null_mean)) %>%
  dplyr::rename("Mean Null Balanced Accuracy" = "mean_balacc",
                "Analysis Method" = "method") %>%
  knitr::kable(.) %>%
  kableExtra::kable_styling(full_width=F)
```

