---
output: html_document
params:
  data_path: ""
  github_dir: ""
  dataset_ID: ""
  ggseg_atlas: ""
  univariate_feature_set: ""
  pairwise_feature_set: ""
  brain_region_file: ""
  noise_procs: ""
  noise_proc_for_null: ""

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning=F, message=F)
```

```{r}
library(tidyverse)
library(icesTAF)
library(tidyverse)
library(plotly)
library(patchwork)
library(cowplot)

theme_set(theme_cowplot())
```


```{r}
# Parse params
data_path <- params$data_path
github_dir <- params$github_dir
dataset_ID <- params$dataset_ID
ggseg_atlas <- params$ggseg_atlas
univariate_feature_set <- params$univariate_feature_set
pairwise_feature_set <- params$pairwise_feature_set
noise_procs <- params$noise_procs
noise_proc_for_null <- params$noise_proc_for_null
brain_region_file <- params$brain_region_file

# univariate_feature_set <- "catch22"
# pairwise_feature_set <- "pyspi14"
# subject_csv <- "participants.csv"
# github_dir <- "D:/Virtual_Machines/Shared_Folder/github/fMRI_FeaturesDisorders/"
# github_dir <- "~/github/fMRI_FeaturesDisorders/"

# UCLA schizophrenia
# data_path <- "D:/Virtual_Machines/Shared_Folder/PhD_work/data/UCLA_Schizophrenia/"
# data_path <- "~/data/UCLA_Schizophrenia/"
# dataset_ID <- "UCLA_Schizophrenia"
# noise_procs <- c("AROMA+2P", "AROMA+2P+GMR", "AROMA+2P+DiCER")
# noise_proc_for_null <- "AROMA+2P+GMR"

# ABIDE ASD
# data_path <- "D:/Virtual_Machines/Shared_Folder/PhD_work/data/ABIDE_ASD/"
# dataset_ID <- "ABIDE_ASD"
# noise_procs <- c("FC1000")
# noise_proc_for_null <- "FC1000"

rdata_path <- paste0(data_path, "processed_data/Rdata/")
```

```{r}
# Source null distribution functions
source(paste0(github_dir, "helper_functions/Visualization.R"))
```


```{r, results="asis"}
cat("## Pairwise linear SVM results for", dataset_ID, "\n")
```


### Significant results by brain region
```{r, fig.width=6,fig.height=4}
# Main vs. null histogram
SPI_wise_main <- readRDS(paste0(rdata_path, 
                                "SPI_wise_CV_linear_SVM_", 
                                pairwise_feature_set,
                                "_inv_prob_balacc_across_repeats.Rds")) %>%
  dplyr::filter(Noise_Proc == noise_proc_for_null)

# UCLA_Schizophrenia_ROI_wise_model_permutation_null_catch22_inv_prob.Rds
SPI_wise_null <- readRDS(paste0(rdata_path, dataset_ID,
                                "_SPI_wise_model_permutation_null_", 
                                pairwise_feature_set,
                                "_inv_prob.Rds"))

# Pooled empirical null p-values
SPI_wise_pvals <- readRDS(paste0(rdata_path, 
                                 "SPI_wise_CV_linear_SVM_model_permutation_null_", 
                                 pairwise_feature_set,
                                 "_inv_prob_pvals.Rds"))

# Define xmin and xmax
xmin = 0.99 * min(c(min(SPI_wise_main$balanced_accuracy)),
                  c(min(SPI_wise_null$balanced_accuracy)))

xmax = 1.01 * max(c(max(SPI_wise_main$balanced_accuracy)),
                  c(max(SPI_wise_null$balanced_accuracy)))

plot_main_vs_null_bal_acc(main_res = SPI_wise_main,
                          null_res = SPI_wise_null,
                          pvals = SPI_wise_pvals,
                          noise_proc = noise_proc_for_null,
                          xmin = xmin, 
                          xmax = xmax,
                          plot_type = "histogram",
                          grouping_type = "SPI-wise",
                          result_color = "#F0224B") +
  ggtitle("Results vs. Empirical Null Model") +
  theme(legend.position = "right",
        plot.title = element_text(size=13))
```


```{r}
SPI_wise_sig <- SPI_wise_pvals %>%
  filter(bal_acc_p_adj < 0.05)

SPI_wise_sig %>%
  ungroup() %>%
  dplyr::select(grouping_var, balanced_accuracy, bal_acc_p_adj) %>%
  arrange(bal_acc_p_adj) %>%
  dplyr::rename("SPI" = "grouping_var",
                "Balanced Accuracy" = "balanced_accuracy",
                "BH-adjusted p value" = "bal_acc_p_adj") %>%
  knitr::kable(.) %>%
  kableExtra::kable_styling(full_width=F)
```

