#!/bin/bash
#PBS -j oe
#PBS -o /headnode1/abry4213/github/fMRI_FeaturesDisorders/cluster_output/t_statistic_visualizations.txt
#PBS -l select=1:ncpus=4:mem=80GB:mpiprocs=4
#PBS -l walltime=6:00:00
#PBS -M abry4213@uni.sydney.edu.au
#PBS -m a
#PBS -V

cd "$PBS_O_WORKDIR"

# Load anaconda
/usr/physics/Modules/3.2.8/bin/modulecmd bash load Anaconda3-5.1.0 --silent
source /usr/physics/python/anaconda3/etc/profile.d/conda.sh 

conda activate pyspi

# Call python script to perform normalization
Rscript /headnode1/abry4213/github/fMRI_FeaturesDisorders/data_visualisation/t_statistics.R

exit

# Verify the host on which the job ran
hostname


