#!/bin/bash
#PBS -q yossarian
#PBS -N 164_univariate_ROI_wise_null_model_fit
#PBS -j oe
#PBS -o /headnode1/abry4213/github/fMRI_FeaturesDisorders//cluster_output/UCLA_Schizophrenia_null_model_fits/univariate_ROI_wise_null_model_fit_inv_prob_null_model_fit_164_out.txt
#PBS -l select=1:ncpus=1:mem=20GB
#PBS -l walltime=1:00:00
#PBS -m a
#PBS -M abry4213@uni.sydney.edu.au
#PBS -V

cd "$PBS_O_WORKDIR"

# Define directories
github_dir=/headnode1/abry4213/github/fMRI_FeaturesDisorders/
data_path=/headnode1/abry4213/data/UCLA_Schizophrenia/
rdata_path=${data_path}/Rdata/
pydata_path=${data_path}/pydata/
mkdir -p $github_dir/cluster_output/UCLA_Schizophrenia_null_model_fits/

# Change to relevant directory and run our compute script
/usr/physics/R/R-4.2.1/bin/Rscript ${github_dir}/helper_functions/classification/Null_distributions_cluster.R \
--dataset_ID UCLA_Schizophrenia \
--data_path ${data_path} --github_dir ${github_dir} \
--univariate --num_k_folds 10 \
--output_data_dir /headnode1/abry4213/data/UCLA_Schizophrenia/Rdata/UCLA_Schizophrenia_ROI_wise_catch22_inv_prob_null_model_fits/ \
--null_iter_number 164 \
--num_perms_for_iter 1 \
--pairwise_feature_set pyspi_19 \
--univariate_feature_set catch22 \
--svm_kernel linear --grouping_var Brain_Region --svm_feature_var Feature \
--weighting_name inv_prob --use_inv_prob_weighting

exit

# Verify the host on which the job ran
hostname


