---
title: 'Step1: catchaMouse16 data prep'
output: 
  github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load theft:
```{r}
library(theft)
```


split the time-series data into CSVs as input to catchaMouse16:

```{r, eval = F}
source("split_TS_data_into_CSV.R")
```

run `catchaMouse16` using command line

```{bash}
bash run_catchaMouse16.sh
```

merge the output CSV feature files into dataframes that are stored in Rds objects like `theft` output

```{r, eval=F}
source("merge_catchaMouse16_data.R")
```


z-score normalise the catchaMouse16 data

```{r}
# Use the three noise processing methods
noise_procs <- c("AROMA+2P", "AROMA+2P+GMR", "AROMA+2P+DiCER")

for (noise_proc in noise_procs) {
  noise_label = gsub("\\+", "_", noise_proc)
  
  # Load catchaMouse16 data for noise-proc method
  TS_catchaMouse16 <- readRDS(paste0(rdata_path, sprintf("UCLA_%s_catchaMouse16.Rds", 
                                                         noise_label)))
  
  # Z-score normalise
  TS_catchaMouse16_normed <- normalise_feature_frame(TS_catchaMouse16, 
                                                     names_var = "names", 
                                                     values_var = "values", 
                                                     method = "z-score")
  
  # Save resulting z-scored time-series features to an .Rds file
  saveRDS(TS_catchaMouse16_normed, file=paste0(rdata_path, sprintf("UCLA_%s_catchaMouse16_zscored.Rds", 
                                                             noise_label)))
}
```

