#!/bin/bash
#PBS -q yossarian
#PBS -N 23_univariate_Combo_wise_null_model_fit3
#PBS -j oe
#PBS -o /headnode1/abry4213/github//fMRI_FeaturesDisorders/cluster_output/UCLA_Schizophrenia_null_model_fits/univariate_Combo_wise_null_model_fit3_inv_prob_null_model_fit_23_out.txt
#PBS -l select=1:ncpus=1:mem=20GB
#PBS -l walltime=12:00:00
#PBS -m a
#PBS -M abry4213@uni.sydney.edu.au
#PBS -V

cd "$PBS_O_WORKDIR"

# Define directories
github_dir=/headnode1/abry4213/github/
data_path=/headnode1/abry4213/data/UCLA_Schizophrenia/
rdata_path=/headnode1/abry4213/data/UCLA_Schizophrenia/processed_data_run3/Rdata/
pydata_path=${data_path}/pydata/
mkdir -p $github_dir/fMRI_FeaturesDisorders/cluster_output/UCLA_Schizophrenia_null_model_fits/

# Change to relevant directory and run our compute script
/usr/physics/R/R-4.2.1/bin/Rscript ${github_dir}/fMRI_FeaturesDisorders/helper_functions/classification/Null_distributions_cluster.R \
--dataset_ID UCLA_Schizophrenia \
--data_path ${data_path} \
--rdata_path ${rdata_path} \
--github_dir ${github_dir} \
--sample_metadata_file UCLA_Schizophrenia_sample_metadata.Rds \
--univariate --num_k_folds 10 \
--output_data_dir /headnode1/abry4213/data/UCLA_Schizophrenia/processed_data_run3/Rdata/UCLA_Schizophrenia_Combo_wise_catch22_inv_prob_null_model_fits/ \
--null_iter_number 23 \
--num_perms_for_iter 10 \
--pairwise_feature_set pyspi14 \
--univariate_feature_set catch22 \
--noise_proc AROMA+2P+GMR \
--svm_kernel linear \
--grouping_var Combo \
--svm_feature_var Combo \
--weighting_name inv_prob --use_inv_prob_weighting

exit

# Verify the host on which the job ran
hostname


