---
title: "exploring theft"
author: "Annie Bryant"
date: "5/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(theft)
library(tidyverse)
rdata_path <- "D:/Virtual_Machines/Shared_Folder/PhD_work/data/scz/UCLA/Rdata/"
```


Take 20 schizophrenia subjects and 20 controls from UCLA AROMA+2P dataset
```{r}
# Load TS data for AROMA+2P
ts_data <- readRDS(paste0(rdata_path, "UCLA_AROMA_2P.Rds"))

# Sample 20 per diagnosis group
set.seed(127)
example_subjects <- ts_data %>%
  group_by(Subject_ID) %>%
  filter(!all(value == 0)) %>%
  ungroup() %>%
  distinct(Subject_ID, diagnosis) %>%
  group_by(diagnosis) %>%
  sample_n(20)

example_subj_ts_data <- ts_data %>%
  semi_join(., example_subjects) %>%
  filter(Brain_Region == "ctx-lh-lateralorbitofrontal")

# Run catch22
feature_matrix <- calculate_features(data = example_subj_ts_data, 
                                     id_var = "Subject_ID", 
                                     time_var = "timepoint", 
                                     values_var = "value", 
                                     group_var = "diagnosis", 
                                     feature_set = "catch22",
                                     seed = 127)

```

```{r}
plot_feature_matrix(feature_matrix, 
                    is_normalised = FALSE, 
                    id_var = "id", 
                    method = "z-score",
                    interactive = FALSE)
```

```{r}
# PCA visualization
plot_low_dimension(feature_matrix, 
                   is_normalised = FALSE, 
                   id_var = "id", 
                   group_var = "group", 
                   method = "z-score", 
                   low_dim_method = "PCA", 
                   plot = TRUE,
                   show_covariance = TRUE,
                   seed = 123)
```

```{r}
# tSNE visualization
plot_low_dimension(feature_matrix, 
                   is_normalised = FALSE, 
                   id_var = "id", 
                   group_var = "group", 
                   method = "z-score", 
                   low_dim_method = "t-SNE", 
                   perplexity = 10, 
                   plot = TRUE,
                   show_covariance = FALSE,
                   seed = 123)
```

```{r}
# Pearson
plot_ts_correlations(example_subj_ts_data, 
                     is_normalised = FALSE, 
                     id_var = "Subject_ID", 
                     time_var = "timepoint",
                     values_var = "value",
                     method = "z-score",
                     cor_method = "pearson",
                     interactive = FALSE)
```

```{r}
# Spearman
plot_ts_correlations(example_subj_ts_data, 
                     is_normalised = FALSE, 
                     id_var = "Subject_ID", 
                     time_var = "timepoint",
                     values_var = "value",
                     method = "z-score",
                     cor_method = "spearman",
                     interactive = FALSE)
```

```{r}
# Feature vector correlations
plot_feature_correlations(feature_matrix, 
                          is_normalised = FALSE, 
                          id_var = "id", 
                          names_var = "names",
                          values_var = "values",
                          method = "z-score",
                          cor_method = "pearson",
                          interactive = FALSE)
```

```{r}
# In-sample with model-free shuffles + balanced accuracy
in_sample_model_free_shuffles <- compute_top_features(feature_matrix, 
                                id_var = "id", 
                                group_var = "group",
                                num_features = 10, 
                                normalise_violin_plots = FALSE,
                                method = "z-score",
                                cor_method = "pearson",
                                test_method = "svmLinear",
                                use_balanced_accuracy = TRUE,
                                use_k_fold = FALSE,
                                use_empirical_null =  TRUE,
                                null_testing_method = "model free shuffles",
                                p_value_method = "gaussian",
                                num_permutations = 10000,
                                pool_empirical_null = FALSE,
                                seed = 123)
```

```{r}
# In-sample with null model fits + balanced accuracy
in_sample_null_model_fits <- compute_top_features(feature_matrix, 
                                id_var = "id", 
                                group_var = "group",
                                num_features = 10, 
                                normalise_violin_plots = FALSE,
                                method = "z-score",
                                cor_method = "pearson",
                                test_method = "svmLinear",
                                use_balanced_accuracy = TRUE,
                                use_k_fold = FALSE,
                                use_empirical_null =  TRUE,
                                null_testing_method = "null model fits",
                                p_value_method = "gaussian",
                                num_permutations = 100,
                                pool_empirical_null = FALSE,
                                seed = 123)
```

```{r}
# Cross-validated with model-free shuffles + balanced accuracy
CV_model_free_shuffles <- compute_top_features(feature_matrix, 
                                id_var = "id", 
                                group_var = "group",
                                num_features = 10, 
                                normalise_violin_plots = FALSE,
                                method = "z-score",
                                cor_method = "pearson",
                                test_method = "svmLinear",
                                use_balanced_accuracy = TRUE,
                                use_k_fold = TRUE,
                                num_folds = 10,
                                use_empirical_null =  TRUE,
                                null_testing_method = "model free shuffles",
                                p_value_method = "gaussian",
                                num_permutations = 10000,
                                pool_empirical_null = FALSE,
                                seed = 123)
```

```{r}
# Cross-validated with null model fits + balanced accuracy
CV_model_null_model_fits <- compute_top_features(feature_matrix, 
                                id_var = "id", 
                                group_var = "group",
                                num_features = 10, 
                                normalise_violin_plots = FALSE,
                                method = "z-score",
                                cor_method = "pearson",
                                test_method = "svmLinear",
                                use_balanced_accuracy = TRUE,
                                use_k_fold = TRUE,
                                num_folds = 10,
                                use_empirical_null =  TRUE,
                                null_testing_method = "null model fits",
                                p_value_method = "gaussian",
                                num_permutations = 100,
                                pool_empirical_null = FALSE,
                                seed = 123)
```

```{r}
CV_model_null_model_fits$ResultsTable
```

Save
```{r}
save(in_sample_model_free_shuffles,
     in_sample_null_model_fits,
     CV_model_free_shuffles,
     CV_model_null_model_fits,
     file = paste0(rdata_path, "theft_exploration_mini_dataset.Rdata"))
```

