---
title: "Load in pyspi data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
reticulate::use_python("/home/osboxes/anaconda3/envs/pyspi/bin/python3")
library(tidyverse)
library(reticulate)
source_python("pickle_reader.py")

study <- "/media/sf_Shared_Folder/PhD_work/"
pydata_path <- paste0(study, "data/scz/UCLA/pydata/AROMA_2P/")
output_data_path <- paste0(study, "data/scz/UCLA/pydata/R_files/")

# Load subject metadata
subject_csv <- read.csv(paste0(study, "data/scz/UCLA/participants.csv"))
```

```{r}
if (!file.exists(paste0(pydata_path, "UCLA_AROMA_2P_pyspi_res.Rds"))) {
  pyspi_data_AROMA_2P_list <- list()
  for (subject in unique(list.dirs(pydata_path, recursive = F, full.names = F))) {
    subject_pkl <- extract_df_from_pkl(paste0(pydata_path, subject, "/calc.pkl")) %>%
      mutate(Subject_ID = subject,
             group = subset(subject_csv, sampleID == subject) %>% pull(diagnosis))
    saveRDS(subject_pkl, file=paste0(output_data_path, subject, "_pyspi.Rds"))
    # pyspi_data_AROMA_2P_list <- rlist::list.append(pyspi_data_AROMA_2P_list,
    #                                                subject_pkl)
  }
  # pyspi_data_AROMA_2P <- do.call(plyr::rbind.fill, pyspi_data_AROMA_2P_list)
  # corr_data <- subset(pyspi_data_AROMA_2P, SPI == "xcorr_mean_sig-True")
  # saveRDS(pyspi_data_AROMA_2P, file = paste0(pydata_path, "UCLA_AROMA_2P_pyspi_res.Rds"))
  # saveRDS(corr_data, file = paste0(pydata_path, "UCLA_AROMA_2P_pyspi_xcorr.Rds"))
} # else {
#   corr_data <- readRDS(paste0(pydata_path, "UCLA_AROMA_2P_pyspi_xcorr.Rds"))
# }
```

```{r}
subj_data_list <- list()
for (subject in unique(list.dirs(pydata_path, recursive = F, full.names = F))) {
  # Read in subject's data
  subject_data <- readRDS(paste0(output_data_path, subject, "_pyspi.Rds"))
  subj_data_list <- rlist::list.append(subj_data_list, subject_data)
}

all_pyspi_data <- do.call(plyr::rbind.fill, subj_data_list)
saveRDS(all_pyspi_data, paste0(output_data_path, "All_subject_pyspi.Rds"))
```

