#!/bin/bash
#PBS -q yossarian
#PBS -N 95_univariate_catch22_pairwise_pyspi14_corrected_null_model_fit
#PBS -j oe
#PBS -o /headnode1/abry4213/github//fMRI_FeaturesDisorders/cluster_output/UCLA_Schizophrenia_null_model_fits/univariate_catch22_pairwise_pyspi14_corrected_null_model_fit_inv_prob_null_model_fit_95_out.txt
#PBS -l select=1:ncpus=1:mem=20GB
#PBS -l walltime=12:00:00
#PBS -m a
#PBS -M abry4213@uni.sydney.edu.au
#PBS -V

cd "$PBS_O_WORKDIR"

# Define directories
github_dir=/headnode1/abry4213/github/
data_path=/headnode1/abry4213/data/UCLA_Schizophrenia/
rdata_path=/headnode1/abry4213/data/UCLA_Schizophrenia/processed_data/Rdata/
mkdir -p $github_dir/fMRI_FeaturesDisorders/cluster_output/UCLA_Schizophrenia_null_model_fits/

# Change to relevant directory and run our compute script
/usr/physics/R/R-4.2.1/bin/Rscript ${github_dir}/fMRI_FeaturesDisorders/helper_functions/classification/Null_distributions_cluster.R \
--dataset_ID UCLA_Schizophrenia \
--univariate_data_file /headnode1/abry4213/data/UCLA_Schizophrenia/processed_data/Rdata/UCLA_Schizophrenia_catch22_filtered_zscored.Rds \
--univariate_feature_set catch22 \
--pairwise_data_file /headnode1/abry4213/data/UCLA_Schizophrenia/processed_data/Rdata/UCLA_Schizophrenia_pyspi14_corrected_filtered_zscored.Rds \
--pairwise_feature_set pyspi14_corrected \
--data_path ${data_path} \
--rdata_path ${rdata_path} \
--github_dir ${github_dir} \
--sample_metadata_file UCLA_Schizophrenia_sample_metadata.Rds \
--SPI_directionality_file /headnode1/abry4213/github/fMRI_FeaturesDisorders/classification_analysis/pairwise_analysis/SPI_Direction_Info.csv \
--combined_univariate_pairwise \
--num_k_folds 10 \
--output_data_dir /headnode1/abry4213/data/UCLA_Schizophrenia/processed_data/Rdata/UCLA_Schizophrenia_univariate_catch22_pairwise_pyspi14_corrected_inv_prob_null_model_fits/ \
--null_iter_number 95 \
--num_perms_for_iter 5 \
--noise_proc AROMA+2P+GMR \
--svm_kernel linear \
--grouping_var GROUPING_VAR \
--svm_feature_var SVM_FEATURE_VAR \
--weighting_name inv_prob \
--use_inv_prob_weighting

exit

# Verify the host on which the job ran
hostname


