---
title: "figures"
author: "Annie Bryant"
date: '2022-06-11'
output: html_document
---

```{r}
library(tidyverse)
github_dir <- "D:/Virtual_Machines/Shared_Folder/github/fMRI_FeaturesDisorders/"
source(paste0(github_dir, "helper_functions/Linear_SVM.R"))
source(paste0(github_dir, "helper_functions/Visualization.R"))
source(paste0(github_dir, "helper_functions/Null_distributions.R"))

rdata_path <- "D:/Virtual_Machines/Shared_Folder/PhD_work/data/scz/UCLA/Rdata/"
set.seed(127)
```

# Figure 1 

methods

# Figure 2

## Univariate

### ROI-wise

```{r}
ROI_wise_data <- readRDS(paste0(rdata_path,
                                "ROI_wise_CV_linear_SVM_catch22_inv_prob.Rds")) %>%
  filter(Noise_Proc == "AROMA+2P+GMR",
         Sample_Type == "Out-of-sample") %>%
  mutate(Type = "Main")

ROI_wise_data_null <- readRDS(paste0(rdata_path,
                                     "ROI_wise_model_permutation_null_catch22_inv_prob.Rds")) %>%
  filter(Noise_Proc == "AROMA+2P+GMR",
         Sample_Type == "Out-of-sample")

plyr::rbind.fill(ROI_wise_data, ROI_wise_data_null) %>%
  mutate(pvalue_percentile = quantile(balanced_accuracy[Type == "null"], 
                                      probs = c(0.95))) %>%
  ggplot(data=., mapping=aes(x = balanced_accuracy)) +
  geom_histogram(aes(fill = Type, y = ..density..),
                 position = "identity", alpha = 0.6, 
                 bins = 50) +
  ggtitle("ROI-wise CV linear SVM with catch22") +
  labs(fill = "") +
  ylab("Density") +
  xlab("10-fold CV Balanced Accuracy") +
  scale_fill_manual(values = c("red", "gray60")) +
  geom_vline(aes(xintercept = pvalue_percentile), linetype = 2) +
  theme(legend.position = "bottom",
        plot.title = element_text(hjust=0.5))
ggsave("figure_plots/ROI_wise_CV_linear_SVM_catch22.png",
       width = 5, height = 4, units = "in", dpi = 300)
```

### Feature-wise

```{r}
Feature_wise_data <- readRDS(paste0(rdata_path,
                                "Feature_wise_CV_linear_SVM_catch22_inv_prob.Rds")) %>%
  filter(Noise_Proc == "AROMA+2P+GMR",
         Sample_Type == "Out-of-sample") %>%
  mutate(Type = "Main")

Feature_wise_data_null <- readRDS(paste0(rdata_path,
                                     "Feature_wise_model_permutation_null_catch22_inv_prob.Rds")) %>%
  filter(Noise_Proc == "AROMA+2P+GMR",
         Sample_Type == "Out-of-sample")

plyr::rbind.fill(Feature_wise_data, Feature_wise_data_null) %>%
  mutate(pvalue_percentile = quantile(balanced_accuracy[Type == "null"], 
                                      probs = c(0.95))) %>%
  ggplot(data=., mapping=aes(x = balanced_accuracy)) +
  geom_histogram(aes(fill = Type, y = ..density..),
                 position = "identity", alpha = 0.6, 
                 bins = 50) +
  ggtitle("Feature-wise CV linear SVM with catch22") +
  labs(fill = "") +
  ylab("Density") +
  xlab("10-fold CV Balanced Accuracy") +
  scale_fill_manual(values = c("red", "gray60")) +
  geom_vline(aes(xintercept = pvalue_percentile), linetype = 2) +
  theme(legend.position = "bottom",
        plot.title = element_text(hjust=0.5))
ggsave("figure_plots/Feature_wise_CV_linear_SVM_catch22.png",
       width = 5, height = 4, units = "in", dpi = 300)
```


### Combo-wise

## Pairwise