#!/bin/bash
#PBS -N prepare_pairwise_data
#PBS -q yossarian
#PBS -j oe
#PBS -o /headnode1/abry4213/github/fMRI_FeaturesDisorders/cluster_output/prepare_pairwise_data.txt
#PBS -l select=1:ncpus=1:mem=20GB
#PBS -l walltime=4:00:00
#PBS -M abry4213@uni.sydney.edu.au
#PBS -V

cd "$PBS_O_WORKDIR" 

# Load python
#module load Anaconda3-5.1.0
/usr/physics/Modules/3.2.8/bin/modulecmd bash load Anaconda3-5.1.0 --silent
source /usr/physics/python/anaconda3/etc/profile.d/conda.sh 

conda activate pyspi

# Define directories
github_dir=/headnode1/abry4213/github/
mkdir -p $github_dir/fMRI_FeaturesDisorders/cluster_output/

bash $github_dir/fMRI_FeaturesDisorders/data_prep_and_QC/prepare_pairwise_data.sh

exit

# Verify the host on which the job ran
hostname


