```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=F, message=F)
```

### Source functions
```{r}
rdata_path <- "D:/Virtual_Machines/Shared_Folder/PhD_work/data/scz/UCLA/Rdata/"
library(tidyverse)
library(cowplot)
theme_set(theme_cowplot())
```

Load model-free shuffle null distribution

```{r}
model_free_shuffle_null <- readRDS(paste0(rdata_path, "Null_Model_Free_Shuffles.Rds"))
```

## No reweighting

Load Step 3 ROI-wise results (inverse probability)
```{r}
step3_ROI_wise_acc <- readRDS(paste0(rdata_path, "multivar_ROI_res_svmLinear_CV_e1071.Rds"))
step3_ROI_wise_pvals <- readRDS(paste0(rdata_path, "ROI_wise_10FCV_linear_SVM_e1071_pvals.Rds"))

step3_ROI_wise_res <- left_join(step3_ROI_wise_acc, step3_ROI_wise_pvals) %>%
  dplyr::select(grouping_var, Noise_Proc, balanced_accuracy, bal_acc_p, bal_acc_p_adj) %>%
  filter(Noise_Proc == "AROMA+2P") %>%
  mutate(balanced_accuracy = 100*round(balanced_accuracy, 4),
         bal_acc_p = scales::scientific(bal_acc_p, digits = 3),
         bal_acc_p_adj = scales::scientific(bal_acc_p_adj, digits = 3),
         Method = "i: ROI-wise") %>%
  arrange(desc(balanced_accuracy))

step3_ROI_wise_res

write.csv(step3_ROI_wise_res, "Step3_summary.csv", row.names = F)
```


```{r}
step4_feature_wise_acc <- readRDS(paste0(rdata_path, "feature_wise_multi_ROI_svmLinear_CV_e1071.Rds"))
step4_feature_wise_pvals <- readRDS(paste0(rdata_path, "Feature_wise_10FCV_linear_SVM_e1071_pvals.Rds"))

step4_feature_wise_res <- left_join(step4_feature_wise_acc, step4_feature_wise_pvals) %>%
  dplyr::select(grouping_var, Noise_Proc, balanced_accuracy, bal_acc_p, bal_acc_p_adj) %>%
  filter(Noise_Proc == "AROMA+2P") %>%
  mutate(balanced_accuracy = 100*round(balanced_accuracy, 4),
         bal_acc_p = scales::scientific(bal_acc_p, digits = 3),
         bal_acc_p_adj = scales::scientific(bal_acc_p_adj, digits = 3),
         Method = "ii: Feature-wise") %>%
  arrange(desc(balanced_accuracy))
step4_feature_wise_res

write.csv(step4_feature_wise_res, "Step4_summary.csv", row.names = F)
```

Load Step 5 Combo-wise results

```{r}
step5_combo_wise_acc <- readRDS(paste0(rdata_path, "combo_wise_multi_ROI_svmLinear_CV_e1071.Rds"))
step5_combo_wise_pvals <- readRDS(paste0(rdata_path, "Combo_wise_10FCV_linear_SVM_e1071_pvals.Rds"))
noise_procs = c("AROMA+2P", "AROMA+2P+GMR", "AROMA+2P+DiCER")

step5_combo_wise_res <- left_join(step5_combo_wise_acc, step5_combo_wise_pvals) %>%
  dplyr::select(Noise_Proc, balanced_accuracy, bal_acc_p, bal_acc_p_adj) %>%
  mutate(balanced_accuracy = 100*round(balanced_accuracy, 4),
         bal_acc_p = scales::scientific(bal_acc_p, digits = 3),
         bal_acc_p_adj = scales::scientific(bal_acc_p_adj, digits = 3),
         Method = "iii: Combo-wise",
         Noise_Proc = factor(Noise_Proc, levels = noise_procs)) %>%
  arrange(Noise_Proc)
step5_combo_wise_res

write.csv(step5_combo_wise_res, "Step5_summary.csv", row.names = F)
```

```{r}
do.call(plyr::rbind.fill,
                    list(step3_ROI_wise_res,
                         step4_feature_wise_res,
                         step5_combo_wise_res)) %>%
  mutate(Method = factor(Method, levels = c("i: ROI-wise",
                                            "ii: Feature-wise",
                                            "iii: Combo-wise"))) %>%
  ggplot(data=., mapping=aes(x=balanced_accuracy, fill=Method)) +
  geom_histogram(alpha=0.6, position="identity") +
  ylab("Number of Trials") +
  xlab("10-fold CV Balanced Accuracy") +
  theme(legend.position="bottom")
ggsave("plots/Balanced_Accuracy_Distribution_10FCV_linear_SVM_e1071.png",
       width=6, height=4, units="in", dpi=300)
```

## Inverse probability

Load Step 3 ROI-wise results (inverse probability)
```{r}
step3_ROI_wise_acc_inv_prob <- readRDS(paste0(rdata_path, "multivar_ROI_res_svmLinear_CV_e1071_inv_prob.Rds"))
step3_ROI_wise_pvals_inv_prob <- readRDS(paste0(rdata_path, "ROI_wise_10FCV_linear_SVM_e1071_inv_prob_pvals.Rds"))

step3_ROI_wise_res_inv_prob <- left_join(step3_ROI_wise_acc_inv_prob, step3_ROI_wise_pvals_inv_prob) %>%
  dplyr::select(grouping_var, Noise_Proc, balanced_accuracy, bal_acc_p, bal_acc_p_adj) %>%
  filter(Noise_Proc == "AROMA+2P") %>%
  mutate(balanced_accuracy = 100*round(balanced_accuracy, 4),
         bal_acc_p = scales::scientific(bal_acc_p, digits = 3),
         bal_acc_p_adj = scales::scientific(bal_acc_p_adj, digits = 3),
         Method = "i: ROI-wise") %>%
  arrange(desc(balanced_accuracy))

step3_ROI_wise_res_inv_prob

write.csv(step3_ROI_wise_res_inv_prob, "Step3_summary_inv_prob.csv", row.names = F)
```


Load Step 4 Feature-wise results

```{r}
step4_feature_wise_acc_inv_prob <- readRDS(paste0(rdata_path, "feature_wise_multi_ROI_svmLinear_CV_e1071_inv_prob.Rds"))
step4_feature_wise_pvals_inv_prob <- readRDS(paste0(rdata_path, "Feature_wise_10FCV_linear_SVM_e1071_inv_prob_pvals.Rds"))

step4_feature_wise_res_inv_prob <- left_join(step4_feature_wise_acc_inv_prob, step4_feature_wise_pvals_inv_prob) %>%
  dplyr::select(grouping_var, Noise_Proc, balanced_accuracy, bal_acc_p, bal_acc_p_adj) %>%
  filter(Noise_Proc == "AROMA+2P") %>%
  mutate(balanced_accuracy = 100*round(balanced_accuracy, 4),
         bal_acc_p = scales::scientific(bal_acc_p, digits = 3),
         bal_acc_p_adj = scales::scientific(bal_acc_p_adj, digits = 3),
         Method = "ii: Feature-wise") %>%
  arrange(desc(balanced_accuracy))
step4_feature_wise_res_inv_prob

write.csv(step4_feature_wise_res_inv_prob, "Step4_summary_inv_prob.csv", row.names = F)
```

Load Step 5 Combo-wise results

```{r}
step5_combo_wise_acc_inv_prob <- readRDS(paste0(rdata_path, "combo_wise_multi_ROI_svmLinear_CV_e1071_inv_prob.Rds"))
step5_combo_wise_pvals_inv_prob <- readRDS(paste0(rdata_path, "Combo_wise_10FCV_linear_SVM_e1071_inv_prob_pvals.Rds"))
noise_procs = c("AROMA+2P", "AROMA+2P+GMR", "AROMA+2P+DiCER")

step5_combo_wise_res_inv_prob <- left_join(step5_combo_wise_acc_inv_prob, step5_combo_wise_pvals_inv_prob) %>%
  dplyr::select(Noise_Proc, balanced_accuracy, bal_acc_p, bal_acc_p_adj) %>%
  mutate(balanced_accuracy = 100*round(balanced_accuracy, 4),
         bal_acc_p = scales::scientific(bal_acc_p, digits = 3),
         bal_acc_p_adj = scales::scientific(bal_acc_p_adj, digits = 3),
         Method = "iii: Combo-wise",
         Noise_Proc = factor(Noise_Proc, levels = noise_procs)) %>%
  arrange(Noise_Proc)
step5_combo_wise_res_inv_prob

write.csv(step5_combo_wise_res, "Step5_summary_inv_prob.csv", row.names = F)
```

```{r}
do.call(plyr::rbind.fill,
                    list(step3_ROI_wise_res_inv_prob,
                         step4_feature_wise_res_inv_prob,
                         step5_combo_wise_res_inv_prob)) %>%
  mutate(Method = factor(Method, levels = c("i: ROI-wise",
                                            "ii: Feature-wise",
                                            "iii: Combo-wise"))) %>%
  filter(Noise_Proc == "AROMA+2P") %>%
  ggplot(data=., mapping=aes(x=balanced_accuracy, fill=Method)) +
  geom_histogram(alpha=0.6, position="identity") +
  ylab("Number of Trials") +
  xlab("10-fold CV Balanced Accuracy") +
  theme(legend.position="bottom")
ggsave("plots/Balanced_Accuracy_Distribution_10FCV_linear_SVM_e1071_inv_prob.png",
       width=6, height=4, units="in", dpi=300)
```

## SMOTE

Load Step 3 ROI-wise results (SMOTE)
```{r}
step3_ROI_wise_acc_SMOTE <- readRDS(paste0(rdata_path, "multivar_ROI_res_svmLinear_CV_e1071_SMOTE.Rds")) %>%
  mutate(Method = "i: ROI-wise")
step3_ROI_wise_pvals_SMOTE <- readRDS(paste0(rdata_path, "ROI_wise_10FCV_linear_SVM_e1071_SMOTE_pvals.Rds"))

step3_ROI_wise_res_SMOTE <- left_join(step3_ROI_wise_acc_SMOTE, step3_ROI_wise_pvals_SMOTE) %>%
  dplyr::select(grouping_var, Noise_Proc, balanced_accuracy, bal_acc_p, bal_acc_p_adj) %>%
  filter(Noise_Proc == "AROMA+2P") %>%
  mutate(balanced_accuracy = 100*round(balanced_accuracy, 4),
         bal_acc_p = scales::scientific(bal_acc_p, digits = 3),
         bal_acc_p_adj = scales::scientific(bal_acc_p_adj, digits = 3),
         Method = "i: ROI-wise") %>%
  arrange(desc(balanced_accuracy))

step3_ROI_wise_res_SMOTE

write.csv(step3_ROI_wise_res_SMOTE, "Step3_summary_SMOTE.csv", row.names = F)
```

Load Step 4 Feature-wise results

```{r}
step4_feature_wise_acc_SMOTE <- readRDS(paste0(rdata_path, "feature_wise_multi_ROI_svmLinear_CV_e1071_SMOTE.Rds")) %>%
  mutate(Method = "ii: Feature-wise")
# step4_feature_wise_pvals_SMOTE <- readRDS(paste0(rdata_path, "Feature_wise_10FCV_linear_SVM_e1071_SMOTE_pvals.Rds"))
# 
# step4_feature_wise_res_SMOTE <- left_join(step4_feature_wise_acc_SMOTE, step4_feature_wise_pvals_SMOTE) %>%
#   dplyr::select(grouping_var, Noise_Proc, balanced_accuracy, bal_acc_p, bal_acc_p_adj) %>%
#   filter(Noise_Proc == "AROMA+2P") %>%
#   mutate(balanced_accuracy = 100*round(balanced_accuracy, 4),
#          bal_acc_p = scales::scientific(bal_acc_p, digits = 3),
#          bal_acc_p_adj = scales::scientific(bal_acc_p_adj, digits = 3),
#          Method = "ii: Feature-wise") %>%
#   arrange(desc(balanced_accuracy))
# step4_feature_wise_res_SMOTE
# 
# write.csv(step4_feature_wise_res_SMOTE, "Step4_summary_SMOTE.csv", row.names = F)
```

```{r}
step5_combo_wise_acc_SMOTE <- readRDS(paste0(rdata_path, "combo_wise_multi_ROI_svmLinear_CV_e1071_SMOTE.Rds")) %>%
  mutate(Method = "iii: Combo-wise")
```

```{r}
do.call(plyr::rbind.fill,
                    list(step3_ROI_wise_acc_SMOTE,
                         step4_feature_wise_acc_SMOTE,
                         step5_combo_wise_acc_SMOTE)) %>%
  mutate(Method = factor(Method, levels = c("i: ROI-wise",
                                            "ii: Feature-wise",
                                            "iii: Combo-wise"))) %>%
  filter(Noise_Proc == "AROMA+2P") %>%
  ggplot(data=., mapping=aes(x=100*balanced_accuracy, fill=Method)) +
  geom_histogram(alpha=0.6, position="identity") +
  ylab("Number of Trials") +
  xlab("10-fold CV Balanced Accuracy") +
  theme(legend.position="bottom")
ggsave("plots/Balanced_Accuracy_Distribution_10FCV_linear_SVM_e1071_SMOTE.png",
       width=6, height=4, units="in", dpi=300)
```
